<?php


namespace EasyDb;


class Model extends Builder
{
    /**
     * @var array 字符串时间和时间戳转换
     */
    protected   array   $formatTime     = ['create_time','update_time'];
    protected   bool    $formatTileFlag = false;

    /**
     * @throws \EasyDb\Exception\DbException
     */
    public function __construct($table = null)
    {
        parent::$drive = Db::getDrive();
        parent::__construct($table ?? basename(str_replace('\\', '/', get_class($this))));
        parent::bind(parent::$drive, self::$table);
    }


    public function toArray(): array
    {
        if($this->formatTileFlag){
            $this->_timeFormat();
        }
        return parent::toArray(); // TODO: Change the autogenerated stub
    }

    public function timeFormat($field = []): Model
    {
        $this->formatTileFlag = true;
        !empty($field) && $this->formatTime = $field;
        return $this;
    }

    protected function _timeFormat()
    {
        $array_column = [];
        foreach ($this->formatTime as $key=>$value)
        {
            $array_column[$value] = array_column($this->result,$value);
        }
        foreach ($array_column as $key=>$item){
            foreach ($item as $item_key =>$item_item){
                $array_column[$key][$item_key] = $this->_date($item_item);
                $this->result[$item_key][$key] = $this->_date($item_item);
            }
        }
    }

    protected function _date($time){
        if(strlen($time) == 10){
            return date("Y-m-d H:i:s",$time);
        }
        return $time;
    }

}